# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
    imports = [
        # Include the results of the hardware scan (generated by nixos-generate-config).
        ./hardware.nix

        ./audio.nix
        ./boot.nix
        ./experimental.nix
        ./firewall.nix
        ./locale.nix
        ./network.nix
        ./print.nix
        ./time.nix
        ./touchpad.nix

        ./services
        ./users
    ];

    # Install firefox.
    programs.firefox.enable = true;

    # Allow unfree packages
    nixpkgs.config.allowUnfree = true;

    # List packages installed in system profile. To search, run:
    # $ nix search wget
    environment.systemPackages = with pkgs; [
    #  vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
    #  wget
    ];
}
