# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports =
      [ (modulesPath + "/installer/scan/not-detected.nix")
      ];

    boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "uas" "usb_storage" "usbhid" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
    {
        device = "/dev/disk/by-uuid/5247d08c-9eb3-4d42-9486-592137a85de8";
        fsType = "ext4";
    };

    fileSystems."/boot" =
    {
        device = "/dev/disk/by-uuid/0565-6755";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
    };

    # Boot options for fstab. Search up fstab mount options you can use
    # If you don't have this options attribute, it'll default to "defaults"

    # "users"       # Allows any user to mount and unmount
    # "nofail"      # Prevent system from failing if this drive doesn't mount
    # "x-gvfs-show" # To see the disk in your file explorer (ie GNOME Nautilus).

    fileSystems."/mnt/Games" = {
        device = "/dev/disk/by-uuid/5e42bd38-66a5-459a-aa36-c1d01493847c";
        fsType = "ext4";
        options = [ "rw" "relatime" "exec" "users" "nofail" ];
    };

    swapDevices = [
        {
            device = "/dev/nvme1n1p5";
            # size = 1*1024; # 1 GiB
        }
    ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
