# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports = [
        (modulesPath + "/profiles/qemu-guest.nix")
    ];

    boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" = {
        device = "/dev/disk/by-uuid/da7099f1-7349-4d71-a05f-a202dff0128e";
        fsType = "ext4";
    };

    swapDevices = [
        { device = "/dev/disk/by-uuid/1f5943a7-09b8-4f8a-b2bd-f2ca17d6c495"; }
    ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
