"$schema" = 'https://starship.rs/config-schema.json'

# user1@arch ~>
# root@arch ~#
format = "$username@$hostname~>"
add_newline = true

[username]
format = '[$user]($style)'
show_always = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
