# vim:ft=kitty

## name:     Alacritty
## author:   _
## license:  
## upstream: 
## blurb:    _

# The basic colors
foreground            #d8d8d8
background            #181818
selection_foreground  #181818
selection_background  #d8d8d8

# Cursor colors
cursor                #d8d8d8
cursor_text_color     #181818

# Normal colors
color0  #181818
color1  #ac4242
color2  #90a959
color3  #f4bf75
color4  #6a9fb5
color5  #aa759f
color6  #75b5aa
color7  #d8d8d8

# Bright colors
color8   #6b6b6b
color9   #c55555
color10  #aac474
color11  #feca88
color12  #82b8c8
color13  #c28cb8
color14  #93d3c3
color15  #f8f8f8

# Dim colors
dim_opacity 1.0
color0_dim  #0f0f0f
color1_dim  #712b2b
color2_dim  #5f6f3a
color3_dim  #a17e4d
color4_dim  #456877
color5_dim  #704d68
color6_dim  #4d7770
color7_dim  #8e8e8e

# Colors for marks (marked text in the terminal)
mark1_foreground #181818
mark1_background #ac4242
mark2_foreground #181818
mark2_background #f4bf75

# Tab bar colors
active_tab_foreground   #181818
active_tab_background   #d8d8d8
inactive_tab_foreground #828482
inactive_tab_background #181818