# shell bash
shell_integration no-cursor

window_padding_width 5 17

font_family JetBrainsMono Nerd Font
font_size 20.0
disable_ligatures never

cursor_shape beam

# BEGIN_KITTY_THEME
# Dracula
include current-theme.conf
# END_KITTY_THEME