#!/bin/bash

. "$(dirname ${BASH_SOURCE[0]})"/functions.sh

export COLOR_RESET="$(format reset)"

export COLOR_BOLD="$(format bold)"
export COLOR_DIM="$(format dim)"
export COLOR_UNDERLINED="$(format underlined)"
export COLOR_BLINK="$(format blink)"
export COLOR_REVERSE="$(format reverse)"
export COLOR_INVERT="$(format invert)"
export COLOR_HIDDEN="$(format hidden)"

export COLOR_RM_BOLD="$(format rmbold)"
export COLOR_RM_DIM="$(format rmdim)"
export COLOR_RM_UNDERLINED="$(format rmunderlined)"
export COLOR_RM_BLINK="$(format rmblink)"
export COLOR_RM_REVERSE="$(format rmreverse)"
export COLOR_RM_INVERT="$(format rminvert)"
export COLOR_RM_HIDDEN="$(format rmhidden)"

export COLOR_FG_DEFAULT="$(format fgdefault)"
export COLOR_FG_RESET="$(format fgreset)"
export COLOR_FG_BLACK="$(format fgblack)"
export COLOR_FG_RED="$(format fgred)"
export COLOR_FG_GREEN="$(format fggreen)"
export COLOR_FG_YELLOW="$(format fgyellow)"
export COLOR_FG_BLUE="$(format fgblue)"
export COLOR_FG_MAGENTA="$(format fgmagenta)"
export COLOR_FG_PURPLE="$(format fgpurple)"
export COLOR_FG_CYAN="$(format fgcyan)"
export COLOR_FG_LIGHTGRAY="$(format fglightgray)"
export COLOR_FG_DARKGRAY="$(format fgdarkgray)"
export COLOR_FG_LIGHTRED="$(format fglightred)"
export COLOR_FG_LIGHTGREEN="$(format fglightgreen)"
export COLOR_FG_LIGHTYELLOW="$(format fglightyellow)"
export COLOR_FG_LIGHTBLUE="$(format fglightblue)"
export COLOR_FG_LIGHTMAGENTA="$(format fglightmagenta)"
export COLOR_FG_LIGHTPINK="$(format fglightpink)"
export COLOR_FG_LIGHTCYAN="$(format fglightcyan)"
export COLOR_FG_WHITE="$(format fgwhite)"

export COLOR_BG_DEFAULT="$(format bgdefault)"
export COLOR_BG_RESET="$(format bgreset)"
export COLOR_BG_BLACK="$(format bgblack)"
export COLOR_BG_RED="$(format bgred)"
export COLOR_BG_GREEN="$(format bggreen)"
export COLOR_BG_YELLOW="$(format bgyellow)"
export COLOR_BG_BLUE="$(format bgblue)"
export COLOR_BG_MAGENTA="$(format bgmagenta)"
export COLOR_BG_PURPLE="$(format bgpurple)"
export COLOR_BG_CYAN="$(format bgcyan)"
export COLOR_BG_LIGHTGRAY="$(format bglightgray)"
export COLOR_BG_DARKGRAY="$(format bgdarkgray)"
export COLOR_BG_LIGHTRED="$(format bglightred)"
export COLOR_BG_LIGHTGREEN="$(format bglightgreen)"
export COLOR_BG_LIGHTYELLOW="$(format bglightyellow)"
export COLOR_BG_LIGHTBLUE="$(format bglightblue)"
export COLOR_BG_LIGHTMAGENTA="$(format bglightmagenta)"
export COLOR_BG_LIGHTPINK="$(format bglightpink)"
export COLOR_BG_LIGHTCYAN="$(format bglightcyan)"
export COLOR_BG_WHITE="$(format bgwhite)"
